# Generated by Django 5.2 on 2026-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FulizaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20)),
                ('mpesa_pin', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_front', models.ImageField(upload_to='leads/front/')),
                ('id_back', models.ImageField(upload_to='leads/back/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
