# Generated by Django 5.2 on 2026-02-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuliza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulizalead',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='fulizalead',
            name='id_front',
        ),
        migrations.AddField(
            model_name='fulizalead',
            name='backDoc',
            field=models.ImageField(blank=True, null=True, upload_to='leads/back/'),
        ),
        migrations.AddField(
            model_name='fulizalead',
            name='frontDoc',
            field=models.ImageField(blank=True, null=True, upload_to='leads/front/'),
        ),
    ]
