# Generated by Django 5.2 on 2026-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuliza', '0002_remove_fulizalead_id_back_remove_fulizalead_id_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulizalead',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
